name: Cancel Self

on:
  push:
  workflow_dispatch:

jobs:
  task:
    runs-on: ubuntu-latest
    name: Task
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Test Step
        uses: ./ # Uses an action in the root directory
      - run: echo 'Sleeping...'; sleep 120; echo 'Done.';
